---
abstract: 'Tree for Path::Class objects'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Scalar::Util: '0'
  Test::More: '0.94'
  Test::Most: '0'
  perl: '5.010'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.027, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tree-Path-Class
requires:
  Carp: '0'
  Modern::Perl: '0'
  Moose: '2.1400'
  MooseX::Has::Options: '0'
  MooseX::NonMoose: '0'
  MooseX::Types: '0'
  MooseX::Types::Moose: '0'
  MooseX::Types::Path::Class: '0'
  Path::Class: '0'
  Tree: '0'
  namespace::autoclean: '0.16'
  perl: '5.010'
  strict: '0'
  utf8: '0'
resources:
  bugtracker: https://github.com/mjgardner/Tree-Path-Class/issues
  homepage: http://metacpan.org/release/Tree-Path-Class/
  repository: git://github.com/mjgardner/Tree-Path-Class.git
version: '0.006'
x_Dist_Zilla:
  perl:
    version: '5.020001'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '0'
          prefix: ''
          prune_directory: []
          root: .
      name: '@Filter/GatherDir'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Filter/MakeMaker'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::PkgDist
      name: PkgDist
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: '0.005001'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.009'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.009'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: -SingleEncoding
              version: '4.009'
            -
              class: Pod::Weaver::Plugin::StopWords
              name: -StopWords
              version: '1.009'
            -
              class: Pod::Weaver::Section::Region
              name: ':stopwords'
              version: '4.009'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.009'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.009'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: USAGE
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: 'REQUIRED ARGUMENTS'
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: OPTIONS
              version: '4.009'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.009'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.009'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.009'
            -
              class: Pod::Weaver::Section::Collect
              name: TYPES
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: DIAGNOSTICS
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: 'EXIT STATUS'
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: CONFIGURATION
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: 'CONFIGURATION AND ENVIRONMENT'
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: DEPENDENCIES
              version: '4.009'
            -
              class: Pod::Weaver::Section::Generic
              name: INCOMPATIBILITIES
              version: '4.009'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.009'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.009'
            -
              class: Pod::Weaver::Section::Support
              name: Support
              version: '1.007'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.009'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.009'
      name: PodWeaver
      version: '4.006'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@TestingMania/MetaTests'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@TestingMania/Test::Version'
      version: '0.003001'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@TestingMania/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@TestingMania/PodSyntaxTests'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@TestingMania/Test::UnusedVars'
      version: '2.000006'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@TestingMania/PodCoverageTests'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@TestingMania/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: '@TestingMania/Test::Kwalitee'
      version: '2.11'
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@TestingMania/Test::DistManifest'
      version: '2.000004'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
      name: '@TestingMania/Test::EOL'
      version: '0.16'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@TestingMania/Test::NoTabs'
      version: '0.09'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: '0'
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: '0'
          phase: test
          script_finder:
            - ':ExecFiles'
          skips: []
      name: '@TestingMania/Test::Compile'
      version: '2.051'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@TestingMania/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@TestingMania/Test::Perl::Critic'
      version: '2.112410'
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@TestingMania/Test::Synopsis'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@TestingMania/Test::CPAN::Meta::JSON'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@TestingMania/Test::Pod::LinkCheck'
      version: '1.001'
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@TestingMania/MojibakeTests'
      version: '0.7'
    -
      class: Dist::Zilla::Plugin::PerlTidy
      name: PerlTidy
      version: '0.19'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmeAnyFromPod
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmePodInRoot
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: ReportVersions
      version: '1.110730'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: '1.200005'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - README.pod
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Check'
      version: '2.028'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - README.pod
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Commit'
      version: '2.028'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v0.006
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Tag'
      version: '2.028'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Push'
      version: '2.028'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: ''
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: release_build/%b
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::CommitBuild
      version: '2.028'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: '0'
          version_regexp: (?^:^v(.+)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::NextVersion
      version: '2.028'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@GitHub/GitHub::Meta'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@GitHub/GitHub::Update'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.027'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.027'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.027'
